#!/bin/bash
# get dolphinx container
#
# for the first time:
# docker pull ghcr.io/jorgensd/dolfinx-tutorial:v0.8.0
# mkdir docker
# cd docker
# wget https://github.com/jorgensd/dolfinx-tutorial/blob/main/docker/Dockerfile
# cd ..
# wget https://github.com/jorgensd/dolfinx-tutorial/blob/main/pyproject.toml
# docker build -f ./docker/Dockerfile -t local_lab_env .

# docker run --rm -ti -v $(pwd):/root/shared -w /root/shared  --init -p 8888:8888 local_lab_env
docker run --rm -ti --init -p 8888:8888 -v "$(pwd)":/root/shared dolfinx/lab:stable

# from docker docs:
  # --rm                               Automatically remove the container and its associated anonymous volumes when it exits
  # -t, --tty                              Allocate a pseudo-TTY
  # -i, --interactive                      Keep STDIN open even if not attached
  # --init                             Run an init inside the container that forwards signals and reaps processes
  # -p, --publish list                     Publish a container's port(s) to the host
  # -v, --volume list                      Bind mount a volume
